apiVersion: apps/v1
kind: Deployment
metadata:
  name: apigateway
spec:
  replicas: 1
  strategy:
   type: RollingUpdate
   rollingUpdate:
      maxSurge: 1
      maxUnavailable: 24%
  selector:
    matchLabels:
      app: apigateway
  template:
    metadata:
      labels:
        app: apigateway
    spec:
      containers:
      - name: apigateway-container
        image: rcavinash123/apigateway:v1.2.1
        ports:
          - containerPort: 4001
            protocol: TCP
        resources:
          requests:
            memory: 512Mi
          limits:
            memory: 1Gi
        env:
          - name: DEBUG_MODE
            value: "0"
          
